sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: shAtCiv51iZllbFxG4h98vFzGYtBgm/7KyHyy0Mk76r0wYETjbXrXO0URHlyEKSpu0xzjqUmhC8PuRxudsGjg6BFU7Ifrehr06vN0bZFl2NCsJyjaW7/JD/guImNGT/Yfwafv2MfKkOT4wNJGcGoC24pBn9EF/BUePKLO1KzrzUD4sFI2ZnFREurBC61jt9Vf80q0k/SMkO80nOdlewjidsSKYwvEO2P+YKcBwQpV4+r6BI4P7nuRBtemToBS0SYrw009c2IrNSlhdx8NBhtJ2AObElbsn9YoYSMmO4EHWR7A534nVRrt5r+fawcldIRzAcgoOOz6BzxYyltBHefjzW7mMQjDOCrdJh+ad0Z0sOAJF58fTYc8gDvkbTrYxu6j1AcuVHZI7beZfX3U6gfrTDKPbnDAY0/94bUi2QR0f1ZV/dbiU374dmrcNUt+9Wa0hJXmuP4XT4TtHCdyc8zOP748fOVfBm1BbdlhS6L8nmYDvx3YZU5Opd0+wn+N+SkKG6E+jRadMyJiA0DV6G4sV63KDr6yaBrH/hVAErXbSbEF+OXKi/VIM5NutAqTsmZKIUUvJWkvaCjHQPynnk71TN7Y4IsHXlkzIqAlNR1aKCXzZ96wqDgujJ51CazGVNTLhzCRpJ2diXtlteapxuShUgKbn/Qn+lpTqW+MdSJLBc=
  - secure: LF9Gt2RcTThqrQ8xjoO1DjlLcepxGXN/s+IjcQOUul6QypvllfLpxnP30vkriF1v5eU6+iEMfKL4lcSOSEnZ/TEgZ0d3DqOBG0XhTsRWkj1m+NpsI16squvSV9MZzQ7OIy83qbhJrArNWpSMW9wtmZmgFfeh2cfDVZCfW/XgrnirVirNQlZvIaAPl8QGwqHPHVPo9rERLEBDORGY1UTdtCofvm5O0r/rtFR4DmbMVa6mu24DClh8JrS4Q5/KFxWbBMHYfak9GgYWSX9rMMNLcSJ9/3fxDi9aOp6W5MZn+fYMoZn94EqYw+xMCDmu5UDUqe2Vv5WIwR/lY/NY6Mq8SIj2bB8jFFOz7pZbN4wqZJsvbbsS30Fjk/Zv8YVSRsDXS48PEuiiv/qh/retqBonpeWA4Ysguy0OFULz3IJKm3PSBrmVX9VwUQybQfXDUDqeg/Wh2hfNHyfolGfSMmu5ALk1BgcwC+xo1kZU9KKeVTss+XiQFJTX6//Gs7jaVwVvza51GuLWKcHW4iWe0Z5lI2A65rk0w6+A2gLF/duGXPyDnPOyWJXiY9qLyEuQFDqpT3X0d3sYiDNjNP/6Ysyq5hFv02RfwxKdNXL0c4NedaBFqZTWqz04xOev4YUXruxky0oNC/vKPOxqUej6cQCdFP2QTUCPwjyux+FP36L/KZE=
  - secure: HqqtbAFcRHa/5mWkG0pqReSy5kmOnJzCRZWLoiARg7oWq8a0JVGmbYrWEYPu0z1CwdzKIoX/l3rKJf0+1jfvtfMb7etH4qohSmjv+cyfhdSSJoNcviYAfxgFN5+oLu8OoI8YiTvGNvZoHlF2wPytsek6lyC6/WQf/0DPT9uEjkgUWbLdtSrmKk6IvcjyqUFG6Vbiff0S4O8zeVUCEQcg6IWAZX2Gu76qMOJPtEyegqLvnXAokmoTJ23cxNId8P6AEUVo//VInXWaTwk+glmMGQaFjpdF81Js/CNZLGHBx5zofxkg2ILq9s/ww3zT7nXuSOyx5nXYacuG15XfUDPp3pJ3myaJXzG6boQHkUA3AigoVLXrk8+1LqrFCHJe9QeA84YIClOJ4Orm4xS1w3ud+BeY1sFb2ENkEaHARFh1UVLEYhHLEyHXaDOIkqZ8orsa7GDtNXvi8+03dxGqyDtydZz+6CzUezG0NN8xGJO1SLnFA7btqC6j1+7duImvVMPhuJN+0vlrKlfvz7ktYVbKMD29zBAVJ5Gt3RIP0i3ZvRjy7UdG1E1B8FJxPVv4urzJOOX7VebYzkF/skHHtyc5XZYDwsbxbBpiMqA1zy1n6YhLkDhiP1g7zpmOcGjbqnNva16HJj2Wr8XGnLwy4E8fPjyVNVnb1/jmt+h9OYIL69E=
