sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
cache:
  yarn: true
node_js:
- "8"
cache:
- node_modules
before_install:
- export START_TIME=$( date +%s )
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add mgit2 --ignore-workspace-root-check
- mgit sync --resolver-url-template="https://github.com/\${ path }.git"
- git checkout package.json yarn.lock
- rm -rf node_modules
- yarn install
script:
- yarn run test --reporter=dots
- yarn run docs:api --validate-only
- 'if [ $TRAVIS_TEST_RESULT -eq 0 ]; then
    travis_wait yarn run docs:build-and-publish-nightly;
  fi'
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: RO140EQDHmEOPJPikk8eCY5IdHpnEKGm41p5U1ewAbeZv1DpCG+rSumR2JdYl75kFAaZvCSm1NuVMM+kmYd+/z+LQbKj7QH5G/UHNho3H89blIU6WlJhT0YR5vclm9rvnEvOtxnfODca1Qrw+CaCoJks2o4VYbJB7mOBVNsh7Bc=
